name: 'stripe_olap'
version: '1.0.0'
config-version: 2

profile: 'stripe_snowflake'  # must match a profile in ~/.dbt/profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  stripe_olap:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: analytics
      fct_transactions:
        +tags: ["daily"]
      dim_merchant:
        +tags: ["daily"]
      dim_customer:
        +tags: ["daily"]